agents:
  car_assistant:
    enabled: true
    modules:
      - llm
      - multimodal
      - speech
      - rag
    speech:
      use_whisper: true
      tts: vits-ja
    vision:
      object_detector: yolov8
      image_caption: true
    memory:
      max_turns: 3

  translator:
    enabled: true
    modules:
      - llm
      - rag
      - translator_tool
    translator_tool:
      primary: deepL
      fallback: openai
    rag:
      glossary_path: "data/term_glossary.csv"
    memory:
      max_turns: 5